

-------------------------------------------------------------------------
Systeminfo:
CPU:               Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Number of CPUs:    8
RAM:               31.9GB
Diskinfo:          33.5GB/446.5GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 17.11.2024 18:26:32 (UTC +0:00) === ecu.test 2024.4.0.157279+6cc6544af3d9-FeatureSet 157279+6cc6544af3d9 (2024/10/15 14:58:06) (64bit) ===
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] / wx: 4.2.1+tt.5
Protocol: log level Default. Additional logging active: default output

License: ecu.test
         - License options:
             + ecu.test diagnostics
             + trace.check
         - valid up to version: 2024.4
         - valid until: 2025-01-28
         - licensed for: Mahindra_Racing_UK
         - runner: False
         - Server: license01.tracetronic.de



2024-11-17 18:26:32.680 17096 ManagedWorker-1*PE.Run() INFO:
                        Start package '01_StaticTest.pkg' with test case execution with sequential analysis job execution
2024-11-17 18:26:32.689 17096 ManagedWorker-1*PE.Run() INFO:
                        Test case "01_StaticTest" started
2024-11-17 18:26:32.701 17096 ManagedWorker-1*PE.Run() DEBUG:
                        TestEngine: Start ports...
2024-11-17 18:26:32.743 17096 ManagedWorker-1*PE.Run() INFO:
                        Model time mode with continuous simulation activated, time source is port "MDL-DEFAULT01"
2024-11-17 18:26:32.772 17096 ToolLibs ERROR:
                        tts.core.toolingFramework.networking.ToolServerConnector.PrintRemoteException: com_error: (-2147352567, 'Exception occurred.', (0, 'Measurement::Start', 'User interface is busy', '', 17171, -2147418113), None)
2024-11-17 18:26:32.773 17096 ManagedWorker-1*PE.Run() ERROR:
                        tts.testExecution.testSteps.generic.TestStepJobExec.__Call: ToolError: Tool CANoeCANalyzer01 (@local): ExecuteJob() failed: com_error: (-2147352567, 'Exception occurred.', (0, 'Measurement::Start', 'User interface is busy', '', 17171, -2147418113), None)
                        Package "C:\Users\DIL\ecu.test\Workspace\Packages\01_StaticTest.pkg"#2
2024-11-17 18:26:32.824 17096 ManagedWorker-1*PE.Run() ERROR:
                        Test step 2(Execute): "Tool CANoeCANalyzer01 (@local): ExecuteJob() failed: com_error: (-2147352567, 'Exception occurred.', (0, 'Measurement::Start', 'User interface is busy', '', 17171, -2147418113), None)"
                        Package "C:\Users\DIL\ecu.test\Workspace\Packages\01_StaticTest.pkg"#2
2024-11-17 18:26:32.825 17096 ManagedWorker-1*PE.Run() DEBUG_EXC_PRINT:
                        tts.testExecution.engine.TestEngine.ExecuteTestStep: TTError: Tool CANoeCANalyzer01 (@local): ExecuteJob() failed: com_error: (-2147352567, 'Exception occurred.', (0, 'Measurement::Start', 'User interface is busy', '', 17171, -2147418113), None)
                        Package "C:\Users\DIL\ecu.test\Workspace\Packages\01_StaticTest.pkg"#2
2024-11-17 18:26:32.832 17096 ManagedWorker-1*PE.Run() WARNING:
                        Test case "01_StaticTest" aborted
2024-11-17 18:26:32.833 17096 ManagedWorker-1*PE.Run() DEBUG:
                        TestEngine: Stop ports...
2024-11-17 18:26:32.880 17096 ManagedWorker-1*PE.Run() INFO:
                        Test case "01_StaticTest" completed
